name: .NET Build and Test

on:
  push:
    branches: 
      - main 
  pull_request:
    branches: 
      - main
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --no-incremental /WarnAsError
    - name: Test
      env:
        authentication_github_clientId: ${{ secrets.AUTHENTICATION__GITHUB__CLIENTID }}
        authentication_github_clientSecret: ${{ secrets.AUTHENTICATION__GITHUB__CLIENTSECRET }}
      run: dotnet test --no-build --verbosity normal

