name: Deploy chirp

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create-executables:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Go to Chirp CLI project
      run: cd ./Chirp.CLI/
    - name: Publish for windows x64
      run: dotnet publish --runtime win-x64
    - name: Publish for linux x64
      run: dotnet publish --runtime linux-x64
    - name: Publish for MacOS x64
      run: dotnet publish --runtime osx-x64
    - name: Publish for MacOS ARM
      run: dotnet publish --runtime osx-arm64



      
    
