name: Publish on version tags

on:
  push:
    branches: 
      - main
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build_and_test.yml

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/deploy.yml
